// src/lib/v3_schema.ts
// AIU V3 Authoritative Schema, Column Dictionary & Source-to-Database Mapping Specification
// Completely isolated from V2 metadata.

export interface V3ColumnMapping {
  sourceName: string;
  dbName: string;
  dataType: 'TEXT' | 'INTEGER' | 'BIGINT' | 'DECIMAL' | 'DATE' | 'TIMESTAMPTZ';
  isPrimaryKey?: boolean;
  isForeignKey?: boolean;
  references?: {
    table: string;
    column: string;
  };
  nullable: boolean;
  description?: string;
}

export interface V3TableDefinition {
  tableName: string;
  sourceSheetName: string;
  primaryKey: string;
  expectedRowCount: number;
  columns: V3ColumnMapping[];
}

export const V3_TABLES: Record<string, V3TableDefinition> = {
  v3_user_details: {
    tableName: 'v3_user_details',
    sourceSheetName: 'User details',
    primaryKey: 'user_id',
    expectedRowCount: 100,
    columns: [
      { sourceName: 'user ID', dbName: 'user_id', dataType: 'TEXT', isPrimaryKey: true, nullable: false },
      { sourceName: 'Client Code', dbName: 'client_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Account Status Flag', dbName: 'user_account_status_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'User update date', dbName: 'user_update_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'User Equity Allowed', dbName: 'user_equity_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User MF Allowed', dbName: 'user_mf_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User FNO Allowed', dbName: 'user_fno_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Commodity Allowed', dbName: 'user_commodity_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User IPO Allowed', dbName: 'user_ipo_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Loan Allowed', dbName: 'user_loan_allowed', dataType: 'TEXT', nullable: false },
      { sourceName: 'User first Active date', dbName: 'user_first_active_date', dataType: 'DATE', nullable: false },
    ],
  },

  v3_client_details: {
    tableName: 'v3_client_details',
    sourceSheetName: 'Client Details',
    primaryKey: 'client_code',
    expectedRowCount: 100,
    columns: [
      { sourceName: 'client code', dbName: 'client_code', dataType: 'TEXT', isPrimaryKey: true, nullable: false, references: { table: 'v3_user_details', column: 'client_code' } },
      { sourceName: 'Form Number', dbName: 'form_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'customer type(Individual, HUF)', dbName: 'customer_type_individual_huf', dataType: 'TEXT', nullable: false },
      { sourceName: 'Client inward date', dbName: 'client_inward_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client scheme type', dbName: 'client_scheme_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'client inward status', dbName: 'client_inward_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'client inward accept date', dbName: 'client_inward_accept_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client agreement date', dbName: 'client_agreement_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client agent code', dbName: 'client_agent_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client sub agent code', dbName: 'client_sub_agent_code', dataType: 'DECIMAL', nullable: true },
      { sourceName: 'client product type', dbName: 'client_product_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'client icici emp number', dbName: 'client_icici_emp_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'client receipt date', dbName: 'client_receipt_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client form version', dbName: 'client_form_version', dataType: 'TEXT', nullable: false },
      { sourceName: 'client user id', dbName: 'client_user_id', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_user_details', column: 'user_id' } },
      { sourceName: 'client web user id', dbName: 'client_web_user_id', dataType: 'TEXT', nullable: false, description: 'Explicitly excluded from foreign keys per V3 specification' },
      { sourceName: 'client marital status', dbName: 'client_marital_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'client education code', dbName: 'client_education_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client income category code', dbName: 'client_income_category_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client holding range code', dbName: 'client_holding_range_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client customer nri flag', dbName: 'client_customer_nri_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client form 60 flag', dbName: 'client_form_60_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client tax assesse flag', dbName: 'client_tax_assesse_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client verification date', dbName: 'client_verification_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client verify status', dbName: 'client_verify_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'client ack flag', dbName: 'client_ack_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client ack date', dbName: 'client_ack_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client send mail flag', dbName: 'client_send_mail_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client eba upload flag', dbName: 'client_eba_upload_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client eba upload date', dbName: 'client_eba_upload_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client last flag', dbName: 'client_last_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'client rejection mail remarks', dbName: 'client_rejection_mail_remarks', dataType: 'DECIMAL', nullable: true },
      { sourceName: 'client details entered by', dbName: 'client_details_entered_by', dataType: 'DECIMAL', nullable: true },
      { sourceName: 'client details entry date', dbName: 'client_details_entry_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'client details modified by', dbName: 'client_details_modified_by', dataType: 'TEXT', nullable: false },
      { sourceName: 'client details modified date', dbName: 'client_details_modified_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'client pan number', dbName: 'client_pan_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'client category employee code', dbName: 'client_category_employee_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client rm code', dbName: 'client_rm_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client nri category type', dbName: 'client_nri_category_type', dataType: 'TEXT', nullable: true },
      { sourceName: 'client nri base scheme', dbName: 'client_nri_base_scheme', dataType: 'TEXT', nullable: true },
      { sourceName: 'client nri current scheme', dbName: 'client_nri_current_scheme', dataType: 'TEXT', nullable: true },
      { sourceName: 'client non isec agent code', dbName: 'client_non_isec_agent_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'client customer type change date', dbName: 'client_customer_type_change_date', dataType: 'DATE', nullable: false },
      { sourceName: 'client bank type', dbName: 'client_bank_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'client settlement type', dbName: 'client_settlement_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'client demat mandate category', dbName: 'client_demat_mandate_category', dataType: 'TEXT', nullable: true },
      { sourceName: 'client brokerage model flag', dbName: 'client_brokerage_model_flag', dataType: 'TEXT', nullable: false },
    ],
  },

  v3_user_account_information: {
    tableName: 'v3_user_account_information',
    sourceSheetName: 'User Account Information',
    primaryKey: 'form_number',
    expectedRowCount: 100,
    columns: [
      { sourceName: 'Form Number', dbName: 'form_number', dataType: 'TEXT', isPrimaryKey: true, nullable: false, references: { table: 'v3_client_details', column: 'form_number' } },
      { sourceName: 'User Type(Residential, NRI)', dbName: 'user_type_residential_nri', dataType: 'TEXT', nullable: false },
      { sourceName: 'User bank account number', dbName: 'user_bank_account_number', dataType: 'BIGINT', nullable: false },
      { sourceName: 'User bank customer id', dbName: 'user_bank_customer_id', dataType: 'TEXT', nullable: false },
      { sourceName: 'User bank brnch code', dbName: 'user_bank_brnch_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'User bank account type(Self, Joint)', dbName: 'user_bank_account_type_self_joint', dataType: 'TEXT', nullable: false },
      { sourceName: 'User bank account open date', dbName: 'user_bank_account_open_date', dataType: 'DATE', nullable: false },
      { sourceName: 'Client Code', dbName: 'client_code', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_user_details', column: 'client_code' } },
      { sourceName: 'User demat account open date', dbName: 'user_demat_account_open_date', dataType: 'DATE', nullable: false },
      { sourceName: 'User info entered by', dbName: 'user_info_entered_by', dataType: 'TEXT', nullable: false },
      { sourceName: 'User info modified by', dbName: 'user_info_modified_by', dataType: 'TEXT', nullable: false },
      { sourceName: 'User info modified date', dbName: 'user_info_modified_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'user bank account flag', dbName: 'user_bank_account_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'User bank type', dbName: 'user_bank_type', dataType: 'TEXT', nullable: false },
    ],
  },

  v3_user_address_details: {
    tableName: 'v3_user_address_details',
    sourceSheetName: 'User Address Details',
    primaryKey: 'form_number',
    expectedRowCount: 100,
    columns: [
      { sourceName: 'Form Number', dbName: 'form_number', dataType: 'TEXT', isPrimaryKey: true, nullable: false, references: { table: 'v3_client_details', column: 'form_number' } },
      { sourceName: 'Address type (Correspondance , Permanent)', dbName: 'address_type_correspondance_permanent', dataType: 'TEXT', nullable: false },
      { sourceName: 'Address 1', dbName: 'address_1', dataType: 'TEXT', nullable: false },
      { sourceName: 'Address 2', dbName: 'address_2', dataType: 'TEXT', nullable: false },
      { sourceName: 'User City', dbName: 'user_city', dataType: 'TEXT', nullable: false },
      { sourceName: 'User state', dbName: 'user_state', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Country', dbName: 'user_country', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Pin', dbName: 'user_pin', dataType: 'INTEGER', nullable: false },
      { sourceName: 'User telephone Number', dbName: 'user_telephone_number', dataType: 'BIGINT', nullable: false },
      { sourceName: 'User Office Number', dbName: 'user_office_number', dataType: 'BIGINT', nullable: false },
      { sourceName: 'User Mobile Number', dbName: 'user_mobile_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Mail Address Flag', dbName: 'user_mail_address_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Details Entered by', dbName: 'user_details_entered_by', dataType: 'TEXT', nullable: false },
      { sourceName: 'User details entry date', dbName: 'user_details_entry_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'User details modified by', dbName: 'user_details_modified_by', dataType: 'TEXT', nullable: false },
      { sourceName: 'User details modified date', dbName: 'user_details_modified_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'user address same as  correspondance', dbName: 'user_address_same_as_correspondance', dataType: 'TEXT', nullable: false },
      { sourceName: 'User IP', dbName: 'user_ip', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Mobile Relation', dbName: 'user_mobile_relation', dataType: 'TEXT', nullable: false },
      { sourceName: 'User RM  preferred location pin', dbName: 'user_rm_preferred_location_pin', dataType: 'INTEGER', nullable: false },
    ],
  },

  v3_user_personal_details: {
    tableName: 'v3_user_personal_details',
    sourceSheetName: 'User Personal Details',
    primaryKey: 'form_number',
    expectedRowCount: 100,
    columns: [
      { sourceName: 'Form Number', dbName: 'form_number', dataType: 'TEXT', isPrimaryKey: true, nullable: false, references: { table: 'v3_client_details', column: 'form_number' } },
      { sourceName: 'User Type(Applicant, Permanent)', dbName: 'user_type_applicant_permanent', dataType: 'TEXT', nullable: false },
      { sourceName: 'User First name', dbName: 'user_first_name', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Middle Name', dbName: 'user_middle_name', dataType: 'TEXT', nullable: true },
      { sourceName: 'User last name', dbName: 'user_last_name', dataType: 'TEXT', nullable: false },
      { sourceName: 'User DOB', dbName: 'user_dob', dataType: 'DATE', nullable: false },
      { sourceName: 'User Sex', dbName: 'user_sex', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Minor Flag', dbName: 'user_minor_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Email', dbName: 'user_email', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Country Birth', dbName: 'user_country_birth', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Nationality', dbName: 'user_nationality', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Entered Employee Number', dbName: 'user_entered_employee_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Details entered date', dbName: 'user_details_entered_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'User Details modified employee number', dbName: 'user_details_modified_employee_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'Userd details modified date', dbName: 'userd_details_modified_date', dataType: 'TIMESTAMPTZ', nullable: false },
      { sourceName: 'User designation', dbName: 'user_designation', dataType: 'TEXT', nullable: false },
      { sourceName: 'User relation', dbName: 'user_relation', dataType: 'TEXT', nullable: false },
      { sourceName: 'User user id', dbName: 'user_user_id', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_user_details', column: 'user_id' } },
      { sourceName: 'User Income Category', dbName: 'user_income_category', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Marital Status', dbName: 'user_marital_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'User political Connect', dbName: 'user_political_connect', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Inperson verification date', dbName: 'user_inperson_verification_date', dataType: 'DATE', nullable: false },
      { sourceName: 'User customer type', dbName: 'user_customer_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'User update IP', dbName: 'user_update_ip', dataType: 'TEXT', nullable: false },
      { sourceName: 'User update channel', dbName: 'user_update_channel', dataType: 'TEXT', nullable: false },
      { sourceName: 'User US Person', dbName: 'user_us_person', dataType: 'TEXT', nullable: false },
      { sourceName: 'User tax filing country', dbName: 'user_tax_filing_country', dataType: 'TEXT', nullable: false },
      { sourceName: 'User place of birth', dbName: 'user_place_of_birth', dataType: 'TEXT', nullable: false },
      { sourceName: 'User email relation', dbName: 'user_email_relation', dataType: 'TEXT', nullable: false },
      { sourceName: 'User Aadhar last 4 digit', dbName: 'user_aadhar_last_4_digit', dataType: 'INTEGER', nullable: false },
      { sourceName: 'User name as per aadhar', dbName: 'user_name_as_per_aadhar', dataType: 'TEXT', nullable: false },
      { sourceName: 'user aadhar status', dbName: 'user_aadhar_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'user aadhar consent flag', dbName: 'user_aadhar_consent_flag', dataType: 'TEXT', nullable: false },
    ],
  },

  v3_order_details_equity: {
    tableName: 'v3_order_details_equity',
    sourceSheetName: '6. Order Details(Equity)',
    primaryKey: 'order_reference',
    expectedRowCount: 5305,
    columns: [
      { sourceName: 'order reference', dbName: 'order_reference', dataType: 'TEXT', isPrimaryKey: true, nullable: false },
      { sourceName: 'Client code', dbName: 'client_code', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_client_details', column: 'client_code' } },
      { sourceName: 'order exchange code', dbName: 'order_exchange_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'order stock code', dbName: 'order_stock_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'order exchange segment code', dbName: 'order_exchange_segment_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'order flow(buy,sell)', dbName: 'order_flow_buy_sell', dataType: 'TEXT', nullable: false },
      { sourceName: 'order product type', dbName: 'order_product_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'order quantity', dbName: 'order_quantity', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order exchnage segement settlement', dbName: 'order_exchange_segment_settlement', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order lmt market flag', dbName: 'order_lmt_market_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'order lmt rate', dbName: 'order_lmt_rate', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'order disclosed quantity', dbName: 'order_disclosed_quantity', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order status', dbName: 'order_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'order trade date', dbName: 'order_trade_date', dataType: 'DATE', nullable: false },
      { sourceName: 'order ack number', dbName: 'order_ack_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'order executed quantity', dbName: 'order_executed_quantity', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order amount blocked', dbName: 'order_amount_blocked', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'order brokerage value', dbName: 'order_brokerage_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'order isin number', dbName: 'order_isin_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'order placed status', dbName: 'order_placed_status', dataType: 'TEXT', nullable: false },
      { sourceName: 'order quantity blocked', dbName: 'order_quantity_blocked', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order margin percentage', dbName: 'order_margin_percentage', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'order exchange user id', dbName: 'order_exchange_user_id', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order btst settlement number', dbName: 'order_btst_settlement_number', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order btst segment code', dbName: 'order_btst_segment_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'order channel', dbName: 'order_channel', dataType: 'TEXT', nullable: false },
      { sourceName: 'order margin square off mode', dbName: 'order_margin_square_off_mode', dataType: 'TEXT', nullable: false },
      { sourceName: 'order cancel quantity', dbName: 'order_cancel_quantity', dataType: 'INTEGER', nullable: false },
      { sourceName: 'order type', dbName: 'order_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'order valid date', dbName: 'order_valid_date', dataType: 'DATE', nullable: false },
      { sourceName: 'order cal flag', dbName: 'order_cal_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'order exchange ack', dbName: 'order_exchange_ack', dataType: 'TEXT', nullable: false },
      { sourceName: 'order trade value', dbName: 'order_trade_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'order date', dbName: 'order_date', dataType: 'DATE', nullable: false },
    ],
  },

  v3_trade_details_equity: {
    tableName: 'v3_trade_details_equity',
    sourceSheetName: '7. Trade Details(Equity)',
    primaryKey: 'trade_reference',
    expectedRowCount: 5000,
    columns: [
      { sourceName: 'trade reference', dbName: 'trade_reference', dataType: 'TEXT', isPrimaryKey: true, nullable: false },
      { sourceName: 'client code', dbName: 'client_code', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_client_details', column: 'client_code' } },
      { sourceName: 'trade exchange code', dbName: 'trade_exchange_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade stock code', dbName: 'trade_stock_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade exchnage segment code', dbName: 'trade_exchange_segment_code', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade exchange segment settlement', dbName: 'trade_exchange_segment_settlement', dataType: 'INTEGER', nullable: false },
      { sourceName: 'trade order reference', dbName: 'trade_order_reference', dataType: 'TEXT', nullable: false, isForeignKey: true, references: { table: 'v3_order_details_equity', column: 'order_reference' } },
      { sourceName: 'trade date', dbName: 'trade_date', dataType: 'DATE', nullable: false },
      { sourceName: 'trade transaction type', dbName: 'trade_transaction_type', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade flow(Buy,Sell)', dbName: 'trade_flow_buy_sell', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade executed quantity', dbName: 'trade_executed_quantity', dataType: 'INTEGER', nullable: false },
      { sourceName: 'trade executed rate', dbName: 'trade_executed_rate', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade value', dbName: 'trade_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade brokerage value', dbName: 'trade_brokerage_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade net value', dbName: 'trade_net_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade amount blocked', dbName: 'trade_amount_blocked', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade exchange reference', dbName: 'trade_exchange_reference', dataType: 'BIGINT', nullable: false },
      { sourceName: 'trade upload match flag', dbName: 'trade_upload_match_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade contract number', dbName: 'trade_contract_number', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade brokerage flag', dbName: 'trade_brokerage_flag', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade sebi charge value', dbName: 'trade_sebi_charge_value', dataType: 'DECIMAL', nullable: false },
      { sourceName: 'trade user id', dbName: 'trade_user_id', dataType: 'TEXT', nullable: false },
      { sourceName: 'trade transaction charge', dbName: 'trade_transaction_charge', dataType: 'DECIMAL', nullable: false },
    ],
  },
};
